DROP TABLE IF EXISTS rab_room_aksesoris CASCADE;
DROP TABLE IF EXISTS rab_room_finishings CASCADE;
DROP TABLE IF EXISTS rab_room_bahan_bakus CASCADE;
DROP TABLE IF EXISTS rab_rooms CASCADE;
DROP TABLE IF EXISTS rabs CASCADE;
